# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2


jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: environment
            command: env
      - run:
            name: machine traits
            command: |
                echo "uname -a: " $(uname -a)
                echo "free: " $(free -m)
                echo "whoami: " $(whoami)
                echo "ls -l /var/run: " $(ls -l /var/run)
                echo "ls -l /etc/init.d/: " $(ls -l /etc/init.d/)
      - run:
            name: Install Docker client
            command: |
                set -x
                VER="17.03.0-ce"
                curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                mv /tmp/docker/* /usr/bin

