# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

templates:
  # Require docker >=17.05.0-ce for "Allow using build-time args (ARG) in FROM #31352"
  # see: https://circleci.com/docs/2.0/building-docker-images/#docker-version
  # see: https://docs.docker.com/release-notes/docker-ce/#17050-ce-2017-05-04
  docker-daemon: &docker-daemon
    setup_remote_docker:
      version: 17.07.0-ce

jobs:
  build:
    docker:
      - image: docker:dind

    working_directory: ~/repo

    steps:
      - checkout
      # run tests!
      - run:
            name: environment
            command: env
      - run:
            name: machine traits
            command: |
                echo "uname -a: " $(uname -a)
                echo "free: " $(free)
      - run:
            name: find docker stuff
            command: find / -iname *docker* 2>/dev/null || true
      - run:
            name: cat /.dockerenv
            command: cat /.dockerenv
      - run:
          name: run tests
          command: |
            pwd
            docker --version
      - run:
          name: build docker image
          command: |
            # docker build -t trivago/trash:circle .
            # docker --version
            docker search docker
            ls -l /var/lib/docker/

      - store_artifacts:
          path: test-reports
          destination: test-reports
