# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: docker
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
        - version: 17.07.0-ce
      - run:
            name: environment
            command: env
      - run:
            name: machine traits
            command: |
                echo "uname -a: " $(uname -a)
                echo "free: " $(free -m)
                echo "whoami: " $(whoami)
                echo "ls -l /var/run: " $(ls -l /var/run)
                echo "ls -l /etc/init.d/: " $(ls -l /etc/init.d/)
      - run:
            name: check docker
            command: |
                set -x
                docker build .

