# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      # run tests!
      - run:
          name: run tests
          command: |
            env
            pwd
            ./main.py

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - push_docker:
            name: push to dockerhub
            command: |
                echo "where is da forking docker image"

deployment:
  hub:
    branch: master
    commands:
      - docker login -u hsimons -p 1991evev
      - docker push circleci/h4jo_test1

