# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      # run tests!
      - run:
          name: run tests
          command: |
            env
            pwd
            ./main.py

      - store_artifacts:
          path: test-reports
          destination: test-reports

    dependencies:
      override:
        - docker info
        - docker build --rm=false -t h4jo_test1 .

    deployment:
      hub:
        branch: master
        commands:
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker push h4jo_test1

